version: "3.9"

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: StrongPasswordHere
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  laravel-api:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    container_name: laravel-api
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: StrongPasswordHere
      APP_URL: http://localhost:8080
      SANCTUM_STATEFUL_DOMAINS: localhost:5173
      SESSION_DOMAIN: localhost
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

  react-app:
    build:
      context: ./login-app
      dockerfile: Dockerfile
    container_name: react-app
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - laravel-api
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
