# -----------------------------
# Stage 1: Build React app using Vite
# -----------------------------
    FROM node:20-alpine AS builder

    WORKDIR /login-app
    
    COPY login-app/package.json ./
    RUN npm install
    COPY login-app/. .
    RUN npm run build
    
    # -----------------------------
    # Stage 2: Serve using Nginx
    # -----------------------------
    FROM nginx:stable-alpine
    
    RUN rm /etc/nginx/conf.d/default.conf
    
    COPY nginx.conf /etc/nginx/conf.d/default.conf
    
    COPY --from=builder /login-app/dist /var/www/html/
    
    EXPOSE 80
    
    CMD ["nginx", "-g", "daemon off;"]
    